# Generated by Django 4.2.8 on 2023-12-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickleapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='number_of_courts',
            field=models.IntegerField(null=True),
        ),
    ]
