# Generated by Django 4.2.7 on 2023-12-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickleapi', '0003_alter_postcategory_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='court_id',
            new_name='court',
        ),
    ]
