# Generated by Django 4.2.7 on 2023-12-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickleapi', '0004_rename_court_id_post_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='pickleapi.court'),
        ),
    ]
